compile:
	python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. Service.proto




# del archivo generado Service_pb2_grpc.py , reemplazar import Service_pb2 as Service__pb2 por: from . import Service_pb2 as Service__pb2